[package]
name = "risc0-types"
version = "0.1.0"
edition = "2021"

[dependencies]
k256 = {git="https://github.com/risc0/RustCrypto-elliptic-curves", features=["serde"]}
serde = {version="1", default-features=false, features=["derive"]}